sudo: required
services:
  - docker

before_install:
  - docker build -t linmiya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true linmiya/react-test npm test

after_success:
  - docker build -t linmiya/multi-client ./client
  - docker build -t linmiya/multi-nginx ./nginx
  - docker build -t linmiya/multi-server ./server
  - docker build -t linmiya/multi-worker ./worker